### PR TITLE
Response format API test

### PR DESCRIPTION
**Pull request by zhangjg98**
Response formatting of API key test

### CODE REVIEW

**Comment by thecodeofdaniel** [comment]
Test it with the new API key, and try inputting multiple ingredients. Don't write the API key directly within the file itself. Put it in some other file and include it in the .gitignore. Name the file something like "api_key". Then open the file to read the api key. For example...

```
API_KEY = open("api_key", 'r').read()
```

**Comment by zhangjg98** [comment]
Returns null result if I input multiple ingredients at the same time (with a comma separated and with no comma separated). Tried a few different ingredients and all pulled up results. Removed API key from file.

**Comment by thecodeofdaniel** [comment]
You need to insert the api key into the URL. like this...
```
API_KEY = open("api_key.py", 'r').read()
URL = f"www.themealdb.com/api/json/v2/{API_KEY}/filter.php?i="
```

then add the ingredients to the URL to fetch the data

**Comment by thecodeofdaniel** [comment]
> You need to insert the api key into the URL. like this...
> 
> ```
> API_KEY = open("api_key.py", 'r').read()
> URL = f"www.themealdb.com/api/json/v2/{API_KEY}/filter.php?i="
> ```
> 
> then add the ingredients to the URL to fetch the data

try this input `chicken_breast,garlic,salt`

**Comment by andy-ly01** [comment]
> > You need to insert the api key into the URL. like this...
> > ```
> > API_KEY = open("api_key.py", 'r').read()
> > URL = f"www.themealdb.com/api/json/v2/{API_KEY}/filter.php?i="
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then add the ingredients to the URL to fetch the data
> 
> try this input `chicken_breast,garlic,salt`

I removed the read function and created a new py file containing the api key.  The api key now  reads directly into the URL and inputs with multiple ingredients are return results!

**Pull request merged**
